# Generated by Django 3.2.25 on 2025-12-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
    ]
