# Generated by Django 3.2.25 on 2025-12-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quiz_popularity_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_activity_date',
            new_name='last_quiz_date',
        ),
    ]
