# Generated by Django 3.2.25 on 2026-01-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_rename_last_activity_date_userprofile_last_quiz_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
