# Generated by Django 3.2.25 on 2026-01-01 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_quiz_is_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizconfig',
            name='number_of_questions',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
