# Generated by Django 4.2.15 on 2026-01-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_auto_20260102_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('ai_generated', 'AI Generated'), ('file_upload', 'File Upload')], default='ai_generated', max_length=20),
        ),
    ]
